### ISSUE TITLE
JSON file has incorrect mappings

### ISSUE THREAD

**Issue by rmulligan** [aerickt/aerick-phrasing#1]
Hi, Aerick!

I'm trying to create a custom lesson on typey type using your phrase dictionary, but the .json file seems to map to the wrong phrases. 

Could you possibly update that file, or share how you generated it?

Thanks! Nice work.

**Comment by aerickt** [comment]
Hi, it should be fixed now.

**Comment by rmulligan** [comment]
I think it is still missmapped.

Just at the top I see:

"WHAULS":"what you feel",
"WHAULSZ":"what you felt",  

Shouldn't those be WHAUFL and WHAUFLT?

**Comment by aerickt** [comment]
They would be in Jade's phrasing system. I use `-F` as a final medial so I had to move those around. `-LS` is indeed "feel" and `-LSZ` is "felt". This is documented in the README.

**Comment by rmulligan** [comment]
Sorry for the confusion. Thanks for clarifying.
