### ISSUE TITLE
handling is

### ISSUE THREAD

**Issue by Josiah-tan** [aerickt/aerick-phrasing#3]
I noticed that with this system I am no longer able to stroke
"he is", or "she is" which correspond to KWHR-R and SKWHR-R (from the jades system)
you reckon we should add this in (if it hasn't already been added in)? 
Great phrasing system by the way I love it!

**Comment by aerickt** [comment]
oh this is an issue with the json dictionary. Until I can have it fixed, I'd suggest using the python dictionary. You'll have to install the plover-python-dictionary plugin from the plugins manager, restart Plover, and then you can download the python file and add it to Plover like any other dictionary.

**Comment by Josiah-tan** [comment]
thanks for the advice!
